'use client';
import {AreaChart,Area,BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend} from 'recharts';
import {CheckCheck,TriangleAlert} from 'lucide-react';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow,TableCaption} from '@/components/ui/table';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import type {Dataset} from '@/lib/market';
import {diagnose,fmt,pct,type Evidence} from '@/lib/diagnosis';
import {periodName,dateCN,samePeriod,valid} from '@/lib/finance.mjs';
import {filing} from '@/lib/filings';
const tooltipStyle={border:'1px solid #dae4d0',borderRadius:8,fontSize:14,background:'#fff'};
export function FinancialPanel({data,model,open}:{data:Dataset;model:ReturnType<typeof diagnose>;open:(e:Evidence)=>void}){
 const income=data.feeds['000333.SZ:income-statements']?.rows||[];const cash=data.feeds['000333.SZ:cash-flow-statements']?.rows||[];
 const series=income.filter(r=>r.fiscal_period===model.cur?.fiscal_period&&r.period_end_ms<=model.cur?.period_end_ms).sort((a,b)=>a.period_end_ms-b.period_end_ms).map(r=>{const c=samePeriod(cash,r);return {period:periodName(r),profit:valid(r.net_profit)?r.net_profit/1e8:null,cash:c&&valid(c.act_cash_flow_net)?c.act_cash_flow_net/1e8:null};});
 return <section className="panel"><div className="section-heading"><h3>利润与经营现金流</h3><span>人民币亿元 · 同期累计</span></div><p className="muted">仅比较各年度的同一报告期；点击下方结论可核对原始字段与计算公式。</p><div className="chart" role="img" aria-label="各年度同报告期的合并净利润和经营现金流柱状图"><ResponsiveContainer width="100%" height="100%"><BarChart data={series} barGap={10}><CartesianGrid strokeDasharray="3 4" vertical={false} stroke="#e2e8f0"/><XAxis dataKey="period" axisLine={false} tickLine={false} tick={{fontSize:12,fill:'#65758b'}}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:12,fill:'#65758b'}}/><Tooltip contentStyle={tooltipStyle} formatter={(v:any)=>fmt(v)+' 亿元'}/><Legend wrapperStyle={{fontSize:14,paddingTop:10}}/><Bar name="合并净利润" dataKey="profit" fill="#9bb1cd" radius={[5,5,0,0]} maxBarSize={55}/><Bar name="经营现金流" dataKey="cash" fill="#294d76" radius={[5,5,0,0]} maxBarSize={55}/></BarChart></ResponsiveContainer></div><Table className="research-table"><TableCaption>图表数值明细；可在下方现金流证据中核对所选期原始字段。</TableCaption><TableHeader><TableRow><TableHead>可比报告期</TableHead><TableHead>合并净利润（亿元）</TableHead><TableHead>经营现金流（亿元）</TableHead></TableRow></TableHeader><TableBody>{series.map(r=><TableRow key={r.period}><TableCell>{r.period}</TableCell><TableCell>{fmt(r.profit)}</TableCell><TableCell>{fmt(r.cash)}</TableCell></TableRow>)}</TableBody></Table><div className="section-heading" style={{marginTop:30}}><h3>财务证据 · {periodName(model.cur)}</h3><span>查看依据</span></div>{model.evidence.filter(e=>['经营质量','财务趋势','风险'].includes(e.dimension)).map(e=><button className="evidence-row" key={e.id} onClick={()=>open(e)}><span className={'direction '+e.direction}>{e.kind}</span><strong>{e.title}</strong></button>)}</section>;
}
export function PeersPanel({data,model,open}:{data:Dataset;model:ReturnType<typeof diagnose>;open:(e:Evidence)=>void}){
 return <section className="panel"><div className="section-heading"><h3>主要财务指标</h3><span>有限样本 · 非全行业排名</span></div><p className="muted">财务对齐 {periodName(model.cur)}；估值为当前快照（上游时间 {dateCN(data.feeds.valuation?.asOf)}），不随财务期次回溯。</p><Table className="research-table"><TableCaption>三家企业业务组合与地域结构不同。点击公司名称查看财务原始字段，点击 PE 核对估值来源。</TableCaption><TableHeader><TableRow><TableHead>公司 / A 股代码</TableHead><TableHead>营业收入<br/>亿元</TableHead><TableHead>归母同比</TableHead><TableHead>毛利率</TableHead><TableHead>现金流 /<br/>合并净利润</TableHead><TableHead>当前 PE TTM</TableHead></TableRow></TableHeader><TableBody>{model.peers.map(p=><TableRow key={p.code} data-state={p.code==='000333.SZ'?'selected':undefined}><TableCell><button className="company-cell" onClick={()=>open({...model.evidence.find(e=>e.id==='peers')!,title:p.name+' · 同口径财务证据',raw:p.raw})}><strong>{p.name}</strong><small>{p.code} · {p.period}</small></button></TableCell><TableCell>{valid(p.revenue)?fmt(p.revenue/1e8):'缺失'}</TableCell><TableCell>{pct(p.profitGrowth)}</TableCell><TableCell>{valid(p.margin)?fmt(p.margin)+'%':'缺失'}</TableCell><TableCell>{valid(p.cashRatio)?fmt(p.cashRatio)+'×':'不适用'}</TableCell><TableCell><button className="citation" onClick={()=>open(model.evidence.find(e=>e.id==='valuation')!)}>{valid(p.pe)&&p.pe>0?fmt(p.pe)+'×':'不适用'}</button></TableCell></TableRow>)}</TableBody></Table><div className="comparison-note"><CheckCheck size={20}/><div><h4>比较范围</h4><p>三家公司均以家电制造为重要业务，但产品、工业业务和海外收入结构不同。估值差异需结合盈利质量与业务结构解释；历史估值分位尚无数据。</p></div></div></section>;
}
export function MarketPanel({model,days,setDays,open,disabled}:{model:ReturnType<typeof diagnose>;days:string;setDays:(s:string)=>void;open:(e:Evidence)=>void;disabled:boolean}){
 const bars=model.market.bars.map((r:any)=>({...r,date:dateCN(r.date_ms)}));return <section className="panel"><div className="section-heading"><h3>股价走势</h3><Select value={days} onValueChange={setDays} disabled={disabled}><SelectTrigger aria-label="行情区间"><SelectValue/></SelectTrigger><SelectContent>{[20,60,120,240].map(n=><SelectItem key={n} value={String(n)}>最近 {n} 个交易日</SelectItem>)}</SelectContent></Select></div><p className="muted">{bars.length?`${bars[0].date} 至 ${bars.at(-1)?.date}`:'行情缺失'} · 日收盘价 · 前复权 · 元/股</p><div className="market-stats"><button onClick={()=>open(model.evidence.find(e=>e.id==='market')!)}><span>区间价格变化</span><strong>{pct(model.market.change)}</strong></button><button onClick={()=>open(model.evidence.find(e=>e.id==='market')!)}><span>区间最大回撤</span><strong>{valid(model.market.maxDrawdown)?fmt(model.market.maxDrawdown)+'%':'未知'}</strong></button><div><span>实际交易日样本</span><strong>{bars.length}<small>日</small></strong></div></div><div className="chart" role="img" aria-label="美的集团所选区间前复权收盘价折线图"><ResponsiveContainer width="100%" height="100%"><AreaChart data={bars}><defs><linearGradient id="priceFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#668cb7" stopOpacity={.28}/><stop offset="100%" stopColor="#668cb7" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 4" vertical={false} stroke="#e2e8f0"/><XAxis dataKey="date" minTickGap={65} axisLine={false} tickLine={false} tick={{fontSize:12,fill:'#65758b'}}/><YAxis domain={['auto','auto']} axisLine={false} tickLine={false} tick={{fontSize:12,fill:'#65758b'}}/><Tooltip contentStyle={tooltipStyle} formatter={(v:any)=>[fmt(v)+' 元/股','前复权收盘价']}/><Area type="linear" dataKey="close_price" stroke="#294d76" strokeWidth={2} fill="url(#priceFill)" isAnimationActive={false}/></AreaChart></ResponsiveContainer></div><div className="section-heading"><h3>已核实事件</h3><span>资料披露截止 2026-08-29</span></div><button className="event-card" onClick={()=>open(model.evidence.find(e=>e.id==='event')!)}><span>2026.05.06</span><div><h4>境外发行零息可转换债券</h4><p>{filing.event}</p></div></button><div className="warning"><TriangleAlert size={16}/>未接入完整实时新闻与公告流。事件时间与价格波动重合，不能证明因果关系。</div></section>;
}
export function SourcesPanel({data,model}:{data:Dataset;model:ReturnType<typeof diagnose>}){
 return <section className="panel"><div className="section-heading"><h3>来源与统计口径</h3><span>读取于 {new Date(data.fetchedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}</span></div><div className="verification"><h4>公告交叉核对</h4>{model.checks.length?model.checks.map(c=><div key={String(c.label)}><span>{String(c.label)}</span><strong className={c.status==='matched'?'down':'up'}>{c.status==='matched'?'与半年报一致':c.status==='missing'?'接口缺失':'数字冲突 · 暂停综合结论'}</strong></div>):<p>当前选定期尚未整理公告交叉核对，不能视为已验证。</p>}<a href={filing.url+'#page=7'} target="_blank" rel="noreferrer">核对半年报第 7 页 · 原文千元，接口元</a></div><div className="method-grid"><div><h4>财务口径</h4><p>合并报表、人民币。利润和现金流为年初至期末累计；资产负债项目为期末余额。剔除尚未披露或未来期次。</p></div><div><h4>估值与行情</h4><p>TTM 与 MRQ 分开展示。行情使用前复权日收盘价；快照时间是上游有效时间，不能当作最后交易时间。</p></div><div><h4>事实与推断</h4><p>指标由程序计算，AI 仅解读已有证据。AI 文字统一标为分析推断或待验证，关键数字直接查看证据卡。</p></div><div><h4>缺失与过期</h4><p>空值不补零；请求失败不生成正常结论。当前资料不是完整事件流；较旧数据会提示核实最新披露与交易日。</p></div></div><div className="quality-table"><h4>时效与覆盖检查</h4>{model.quality.map(q=><div key={q.id}><strong>{q.label} · {q.asOf}</strong><p>{q.message}</p></div>)}</div><h4 className="source-heading">金融数据请求记录</h4>{Object.values(data.feeds).map(f=><div className="source-row" key={f.id}><strong>{f.id}</strong><span className={f.status==='ok'?'down':'up'}>{f.status==='ok'?`${f.rows.length} 条记录`:f.message}</span><small>上游时间 {dateCN(f.asOf)} · 请求 ID {f.requestId||'无'}</small><a href={f.url} target="_blank" rel="noreferrer">查看查询地址（需要数据权限）</a></div>)}<p className="muted" style={{marginTop:18}}>金融接口需要授权，外部直接打开可能提示鉴权失败；证据面板已呈现本次读取的原始字段、时间和请求编号，密钥不会出现在网页中。</p></section>;
}
