'use client';
import {useEffect,useMemo,useState,useRef} from 'react';
import {RefreshCw,TriangleAlert,BookOpen,Wallet,ChartNoAxesCombined,ShieldQuestion,FileSearch,HelpCircle} from 'lucide-react';
import SiteHeader from '@/components/site-header';
import VerificationPlan from '@/components/verification-plan';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {Button} from '@/components/ui/button';
import type {Dataset} from '@/lib/market';
import {diagnose,fmt,pct,type Evidence} from '@/lib/diagnosis';
import {dateCN,periodName,selectDimensions,valid} from '@/lib/finance.mjs';
import {FinancialPanel,PeersPanel,MarketPanel,SourcesPanel} from '@/components/data-panels';
const labels={positive:'支持证据',negative:'风险线索',conflict:'指标分歧',unknown:'待验证',neutral:'事实信息'};
const questions=[{icon:Wallet,title:'盈利质量',hint:'利润与现金流是否匹配',question:'美的的利润增长，有没有现金流支撑？'},{icon:ChartNoAxesCombined,title:'估值比较',hint:'与格力、海尔的估值差异',question:'和格力、海尔相比，美的估值处于什么位置？'},{icon:ShieldQuestion,title:'潜在风险',hint:'风险信号及待核实事项',question:'美的有哪些矛盾证据与尚未验证的风险？'}];
const detailViews=[{id:'financial',title:'财务数据',hint:'对比历年同期的利润和现金流',icon:Wallet},{id:'peers',title:'同行比较',hint:'比较美的、格力和海尔的关键指标',icon:ChartNoAxesCombined},{id:'market',title:'行情与公告',hint:'切换行情区间，核对已披露事项',icon:BookOpen},{id:'sources',title:'数据来源',hint:'检查数据时间、原始来源和缺失项',icon:FileSearch}];
const fieldNames:Record<string,string>={operating_income:'营业收入',operating_costs:'营业成本',parent_holder_net_profit:'归母净利润',net_profit:'合并净利润',act_cash_flow_net:'经营现金流净额',accounts_receivable:'应收账款',pe_ttm:'市盈率（最近十二个月）'};
export default function Workbench(){
 const [data,setData]=useState<Dataset>();const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [period,setPeriod]=useState('latest');const [days,setDays]=useState('120');const [question,setQuestion]=useState('');const [active,setActive]=useState<Evidence>();const [tab,setTab]=useState('overview');const [ai,setAi]=useState<any>();const [thinking,setThinking]=useState(false);const [aiError,setAiError]=useState('');const [submitted,setSubmitted]=useState('');
 const [history,setHistory]=useState<string[]>([]);const [notes,setNotes]=useState<Record<string,string>>({});
 const answerRef=useRef<HTMLElement>(null);const pageRef=useRef<HTMLDivElement>(null);
 const load=async()=>{setLoading(true);setError('');setAi(undefined);setSubmitted('');setHistory([]);setAiError('');try{const r=await fetch('/api/data');if(!r.ok)throw Error('数据暂时无法加载，请重试。');setData(await r.json());}catch(e){setData(undefined);setError(e instanceof Error?e.message:'连接失败');}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const model=useMemo(()=>data?diagnose(data,period==='latest'?undefined:Number(period),Number(days)):undefined,[data,period,days]);
 const baseRoute=selectDimensions(submitted||question);const route=ai?.focusDimensions?.length?{...baseRoute,dimensions:ai.focusDimensions}:baseRoute;
 const errors=data?Object.values(data.feeds).filter(f=>f.status!=='ok'):[];const conflict=model?.checks.some(c=>c.status==='conflict');const financialBlocked=!!model?.quality.some(q=>q.id==='financial'&&['stale','unknown','missing'].includes(q.status));const core=model?.evidence.find(e=>e.id==='core');const m=model?.metrics;
 const openEvidence=(id:string)=>{const e=model?.evidence.find(e=>e.id===id);if(e)setActive(e);};
 const navigate=(next:string)=>{setTab(next);requestAnimationFrame(()=>pageRef.current?.scrollIntoView({behavior:'smooth',block:'start'}));};
 async function ask(q=question){
  if(q.trim().length<2||thinking||loading)return {status:'not_ready'};
  setQuestion(q);setSubmitted(q);setTab('overview');setThinking(true);setAiError('');setAi(undefined);
  requestAnimationFrame(()=>answerRef.current?.scrollIntoView({behavior:'smooth',block:'start'}));
  try{const r=await fetch('/api/diagnose',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,period:period==='latest'?null:Number(period),days:Number(days),history})});const d:any=await r.json();if(!r.ok)throw Error(d.error||'AI 暂时不可用');setAi(d);setHistory(h=>[...h,q].slice(-3));if(d.data)setData(d.data);return {status:d.guardrail?'guardrail':'complete',summary:d.summary};}catch(e){setAiError(e instanceof Error?e.message:'AI 暂时不可用');return {status:'error',message:e instanceof Error?e.message:'AI 暂时不可用'};}finally{setThinking(false);}
 }
 const actions=useRef({ask,model,thinking,loading});actions.current={ask,model,thinking,loading};
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const register=(t:any)=>{try{Promise.resolve(context.registerTool(t,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
 register({name:'read_diagnosis_evidence',title:'读取当前诊断证据',description:'读取页面当前报告期下的指标证据与未知项，不发送新的分析请求。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:any){if(!input||Object.keys(input).length)throw Error('无效参数');return actions.current.model?{period:periodName(actions.current.model.cur),evidence:actions.current.model.evidence.map(e=>({id:e.id,title:e.title,kind:e.kind,direction:e.direction}))}:{status:'not_ready'};}});
 register({name:'run_equity_diagnosis',title:'运行个股诊断',description:'提交美的集团研究问题，调用 DeepSeek 解读当前证据，将结果显示在页面中。',inputSchema:{type:'object',properties:{question:{type:'string',minLength:2,maxLength:500}},required:['question'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},async execute(input:any){if(!input||Object.keys(input).some(k=>k!=='question')||typeof input.question!=='string'||input.question.trim().length<2||input.question.length>500)throw Error('请输入有效研究问题');if(actions.current.thinking)throw Error('已有诊断正在进行');if(!actions.current.model||actions.current.loading)throw Error('数据尚未就绪');return await actions.current.ask(input.question);}});return ()=>lifecycle.abort();},[]);
 const stale=!!model?.quality.some(q=>['stale','unknown'].includes(q.status));
 const cashKnown=valid(m?.cashRatio);const profitKnown=valid(m?.profitGrowth);
 const snapshot=[
 {id:'growth',icon:ChartNoAxesCombined,topic:'盈利表现',title:profitKnown?(Number(m?.profitGrowth)>0?'归母净利润同比增长':Number(m?.profitGrowth)<0?'归母净利润同比下降':'归母净利润同比持平'):'盈利数据暂缺',text:profitKnown?`本期归母净利润 ${fmt(Number(m?.profit)/1e8)} 亿元，同比 ${pct(m?.profitGrowth)}；营业收入同比 ${pct(m?.revenueGrowth)}。`:'缺少本期或上年同期的数据，暂不下结论。',note:'归母净利润：归属于上市公司股东的利润。',label:'查看盈利依据',tone:'sage'},
 {id:'cash',icon:Wallet,topic:'经营现金流',title:cashKnown?(Number(m?.cashRatio)>1?'经营现金流高于净利润':Number(m?.cashRatio)===1?'经营现金流与净利润相当':'经营现金流低于净利润'):'现金流数据暂缺',text:cashKnown?`本期经营现金流 ${fmt(Number(m?.cfo)/1e8)} 亿元，是合并净利润的 ${fmt(m?.cashRatio)} 倍。`:'缺少可比较的现金流或合并净利润，不能用零值代替。',note:'现金流与利润采用不同口径，需结合回款和支出分析。',label:'查看现金流依据',tone:'sage'},
 {id:core?'core':'inventory',icon:ShieldQuestion,topic:'关注事项',title:core?'归母与扣非利润走势分化':'部分风险信息尚待补充',text:core?'归母净利润增长，扣非归母净利润下降，需结合损益明细理解差异。':'存货、应收账龄和完整实时公告尚未覆盖，不能据此认定没有风险。',note:core?'公司解释涉及汇率损益的会计分类，需结合原文核实。':'相关结论受现有数据范围限制。',label:core?'查看利润差异':'查看信息缺口',tone:'amber'}
 ];
 return <div className="app-shell novice-app">
 <SiteHeader analysis/>
 <main className="workspace novice-workspace" ref={pageRef}>
 <section className="company-intro"><div><div className="intro-kicker">A 股 · 家用电器<span>研究样例</span></div><h1>美的集团 <span>000333.SZ</span></h1><p>经营概览与多维研究</p></div><div className="report-picker"><label>财务报告期</label><Select disabled={thinking||loading} value={period} onValueChange={v=>{setPeriod(v);setHistory([]);setAi(undefined);setSubmitted('');setAiError('');}}><SelectTrigger aria-label="财务报告期"><SelectValue placeholder="正在读取"/></SelectTrigger><SelectContent><SelectItem value="latest">最新 · {periodName(model?.cur)}</SelectItem>{model?.periods.map(p=><SelectItem key={p.period_end_ms} value={String(p.period_end_ms)}>{periodName(p)}</SelectItem>)}</SelectContent></Select><button onClick={load} disabled={loading||thinking}><RefreshCw size={12} className={loading?'spin':''}/>{loading?'正在读取数据':'刷新数据'}</button></div></section>
 {(error||errors.length>0||conflict||stale)&&<div className="warning" role="status"><TriangleAlert size={17}/><span>{error||(conflict?'关键数字与公告不一致，概览和 AI 综合判断暂缓。请先核对来源。':stale?'部分数据时间较旧，请刷新并核实最新披露。':`${errors.length} 项数据暂时缺失，对应问题会显示无法判断。`)} <button onClick={()=>navigate('sources')}>查看原因</button></span></div>}
 <Tabs value={tab} onValueChange={navigate} className="analysis-tabs"><TabsList variant="line" className="analysis-nav" aria-label="研究栏目"><TabsTrigger value="overview">公司概览</TabsTrigger>{detailViews.map(v=><TabsTrigger key={v.id} value={v.id}>{v.title}</TabsTrigger>)}</TabsList><TabsContent value={tab}>
 {tab==='overview'?<>
 <section className="plain-overview" aria-labelledby="overview-title"><div className="overview-heading"><div><h2 id="overview-title">公司概览</h2></div><span className="overview-origin">{loading?'数据加载中':'基于已披露财报'}</span></div>
 {conflict||financialBlocked?<div className="conflict-overview"><h3>{conflict?'关键数字存在冲突，暂停综合判断。':'财务时效或完整性待核实，暂停当前状态判断。'}</h3><p>{conflict?'相同报告期的接口数字与公告原文不一致，核实后再继续。':'请核对来源；历史研究可选择明确的财务报告期。'}</p><Button onClick={()=>navigate('sources')}>核对冲突来源</Button></div>:<div className="snapshot-grid">{snapshot.map(s=><article key={s.id} className={'snapshot-card '+s.tone}><div className="snapshot-topic"><span>{s.topic}</span></div><h3>{loading?'正在读取已披露数据…':s.title}</h3><p>{loading?'正在获取财务数据。':s.text}</p><div className="plain-note">{s.note}</div><button disabled={loading||!model} onClick={()=>openEvidence(s.id)}>{s.label}</button></article>)}</div>}
 <div className="overview-footnote"><span>财务截至 {dateCN(model?.cur?.period_end_ms)} · 累计财务数据</span><button onClick={()=>navigate('sources')}>数据来源</button></div></section>
 {model&&<><section className="evidence-board"><div className="overview-heading"><h2>证据概览</h2><span className="overview-origin">所选报告期 · 非好坏评分</span></div><div className="evidence-groups">{(['positive','negative','conflict','unknown'] as const).map(direction=><article className={'evidence-group '+direction} key={direction}><h3>{({positive:'支持因素',negative:'风险线索',conflict:'指标分歧',unknown:'待验证事项'})[direction]}</h3>{model.evidence.filter(e=>e.direction===direction).map(e=><button key={e.id} onClick={()=>setActive(e)}><span className="kind">{e.kind}</span><span>{e.title}</span></button>)}{!model.evidence.some(e=>e.direction===direction)&&<p>当前资料未识别到此类证据，不代表已排除风险。</p>}</article>)}</div></section><section className="data-scope" aria-label="数据覆盖范围">{model.quality.map(q=><div key={q.id}><strong>{q.label}</strong><span>{q.asOf} · {({available:'阈值内',historical:'历史资料',missing:'缺失',stale:'过期',unknown:'时点未知'})[q.status]}</span></div>)}<p>行情与估值采用 10 个自然日时效阈值，财务采用 200 日；这不是交易日校验。公告仅覆盖所列资料，不代表最新事件全集。</p></section></>}
 <section className="question-section" aria-labelledby="question-title"><div className="overview-heading"><div><h2 id="question-title">研究问答</h2><p>家电制造与多元工业集团 · 财务、同行及公告证据研究</p></div></div><form className="custom-question" onSubmit={e=>{e.preventDefault();ask();}}><label className="sr-only" htmlFor="research-question">研究问题</label><div><input id="research-question" aria-label="研究问题" value={question} disabled={thinking} maxLength={500} onChange={e=>setQuestion(e.target.value)} placeholder="例如：美的的利润增长是否有现金流支撑？"/><Button type="submit" disabled={thinking||loading||question.trim().length<2}>{thinking?'正在分析':'分析'}</Button></div></form><div className="question-choices">{questions.map(q=><button key={q.title} title={q.hint} disabled={thinking||loading||!model} onClick={()=>ask(q.question)} className={submitted===q.question?'chosen':''}>{q.title}</button>)}</div><p className="research-focus">研究重点：{route.dimensions.slice(0,3).join(' · ')}。{route.reason}</p>{history.length>0&&<p className="muted">已关联最近 {history.length} 个研究问题。<button onClick={()=>{setHistory([]);setAi(undefined);setSubmitted('');setQuestion('');}}>开始新问题</button></p>}</section>
 {(submitted||thinking||aiError||ai)&&<section className="guided-answer" ref={answerRef} aria-live="polite"><div className="answer-heading"><div><span className="answer-label">研究问题</span><h2>{submitted||ai?.question}</h2></div></div>
 {thinking&&<div className="thinking-state" role="status"><RefreshCw size={18} className="spin"/><div><strong>正在分析…</strong><p>正在核对财务指标与相关证据，通常需要数秒。</p></div></div>}
 {aiError&&<div className="answer-error"><TriangleAlert size={20}/><div><h3>分析暂不可用</h3><p>{aiError}</p><p>财务数据与原始来源仍可查阅。</p><Button onClick={()=>ask(submitted)} disabled={thinking}>重新分析</Button></div></div>}
 {ai&&<><div className="answer-summary"><span className="kind">{ai.guardrail?'研究范围说明':'AI 组织的证据解读'}</span><h3>分析摘要</h3>{ai.counterpointSupplemented&&<p className="muted">系统已补充必须核对的反证或未知项。</p>}{ai.scope==='limited'&&<p className="warning">当前资料不能完整回答该问题。以下仅列相关线索，需按验证路径补充原文。</p>}{ai.summaryItems?.length?<div>{ai.summaryItems.map((item:any)=><div className="summary-item" key={item.id}><p>{item.text}</p><button onClick={()=>openEvidence(item.id)}>核对依据 · {labels[item.direction as keyof typeof labels]}</button></div>)}</div>:<p>{ai.summary}</p>}</div><div className="answer-claims">{ai.claims?.map((c:any,i:number)=><article key={i}><div className="claim-heading"><strong>{c.kind==='待验证'?'待核实事项':'分析依据'}</strong><small>{c.kind}</small></div><p>{c.text}</p><div className="claim-evidence">{c.evidenceIds?.map((id:string)=><button key={id} onClick={()=>openEvidence(id)}><FileSearch size={13}/>{model?.evidence.find(e=>e.id===id)?.title||'查看相关证据'}</button>)}</div></article>)}</div><div className="answer-next"><h3>相关问题</h3>{ai.questions?.map((q:string)=><button key={q} onClick={()=>ask(q)} disabled={thinking}>{q}</button>)}</div><Accordion type="single" collapsible className="method-accordion"><AccordionItem value="route"><AccordionTrigger>分析维度与方法</AccordionTrigger><AccordionContent><p>{route.reason}</p><div className="route-tags">{route.dimensions.map((d:string,i:number)=><button key={d} onClick={()=>{const e=model?.evidence.find(e=>e.dimension===d);if(e)setActive(e);}}>{i+1}. {d}</button>)}</div><p className="muted">AI 根据问题选择与组织解读，数字、解释条款和边界来自当前证据库；不展示模型自由生成的新事实。未通过结构和反证校验时明确报错。</p></AccordionContent></AccordionItem></Accordion></>}
 </section>}

 <Accordion type="single" collapsible className="glossary"><AccordionItem value="terms"><AccordionTrigger><span><HelpCircle size={16}/>术语说明</span></AccordionTrigger><AccordionContent><dl><div><dt>同比</dt><dd>与去年同一段时间比较。例如，上半年对比去年上半年。</dd></div><div><dt>归母净利润 / 合并净利润</dt><dd>前者是属于上市公司股东的利润；后者还包括属于少数股东的部分。与集团现金流比较时用后者。</dd></div><div><dt>扣非归母净利润</dt><dd>从归母利润中剔除按规则认定的非经常性损益。它与归母利润可能出现不同变化，不能只看其中一个。</dd></div><div><dt>经营现金流</dt><dd>经营活动产生的现金净流入或净流出，帮助判断账面利润与现金是否匹配。</dd></div><div><dt>市盈率（PE TTM）</dt><dd>股价相对最近十二个月每股收益的倍数。需要结合增长、风险和同行差异，不能简单理解为越低越好。</dd></div></dl></AccordionContent></AccordionItem></Accordion>
 </>:<section className="detail-workspace"><div className="detail-intro"><h2>{detailViews.find(v=>v.id===tab)?.title}</h2><p>{detailViews.find(v=>v.id===tab)?.hint}</p></div>{data&&model?<>{tab==='financial'&&<FinancialPanel data={data} model={model} open={setActive}/ >}{tab==='peers'&&<PeersPanel data={data} model={model} open={setActive}/ >}{tab==='market'&&<MarketPanel model={model} days={days} setDays={v=>{setDays(v);setHistory([]);setAi(undefined);setSubmitted('');}} open={setActive} disabled={thinking}/ >}{tab==='sources'&&<SourcesPanel data={data} model={model}/ >}</>:<div className="panel">{loading?'数据加载中…':'数据暂不可用，请刷新重试。'}</div>}</section>}
 </TabsContent></Tabs>
 <footer className="footer novice-footer"><span>见微 · 仅供研究参考，不构成投资建议</span><span>财务与行情 / 扶摇　公告 / 深交所、巨潮资讯　AI / DeepSeek</span></footer>
 </main>
 <Sheet open={!!active} onOpenChange={o=>{if(!o)setActive(undefined);}}><SheetContent className="evidence-sheet plain-sheet"><SheetHeader><span className="small-label">证据详情</span><SheetTitle>{active?.title}</SheetTitle><SheetDescription>{active?.kind} · {active?labels[active.direction]:''}</SheetDescription></SheetHeader><div className="sheet-body"><h4>内容摘要</h4><p>{active?.body}</p><h4>适用范围</h4><p>{active?.boundary}</p><Accordion type="multiple" className="evidence-accordion"><AccordionItem value="numbers"><AccordionTrigger>原始数据与计算口径<span className="evidence-count">{active?.raw.length||0} 项</span></AccordionTrigger><AccordionContent><p className="formula">{active?.formula}</p>{active?.raw.length?active.raw.map((r,i)=><div className="raw-card" key={i}><strong>{fieldNames[r.field]||r.field}</strong><b>{typeof r.value==='number'?r.value.toLocaleString('zh-CN',{maximumFractionDigits:6}):r.value??'缺失'}</b><span>{r.unit} · {r.period}</span><small>{r.source} · 披露 {r.published||'不适用'}</small><a href={r.url} target="_blank" rel="noreferrer">{r.url.includes('.PDF')?'阅读公告原文':'查看金融数据查询地址'}</a><small>原始字段：{r.field}{r.requestId?' · 请求编号：'+r.requestId:''}</small></div>):<p className="warning">目前没有足够证据。数据缺失不代表没有风险。</p>}<p className="muted">公告链接可直接阅读；金融接口地址需要数据权限，这里已展示本次读取的原始字段。</p></AccordionContent></AccordionItem></Accordion>{active&&<VerificationPlan key={active.id} evidence={active} note={notes[`${model?.cur?.period_end_ms}:${active.id}:${active.title}`]||''} onSave={text=>setNotes(n=>({...n,[`${model?.cur?.period_end_ms}:${active.id}:${active.title}`]:text}))} onNavigate={target=>{setActive(undefined);navigate(target);}}/>}<div className="next-question"><strong>相关研究问题</strong><p>{active?.next}</p><Button onClick={()=>{const q=active?.next;setActive(undefined);if(q)ask(q);}}>继续分析</Button></div></div></SheetContent></Sheet>
 </div>;
}
