import type { Dataset, Row } from './market';
import {growth,ratio,margin,difference,periodName,samePeriod,priceStats,dateCN,valid} from './finance.mjs';
import {filing} from './filings';
import {assessQuality} from './research';
export type Raw={field:string;value:number|string|null;unit:string;period:string;source:string;url:string;published?:string;requestId?:string};
export type Evidence={id:string;title:string;body:string;dimension:string;direction:'positive'|'negative'|'conflict'|'unknown'|'neutral';kind:'事实'|'分析推断'|'待验证';value?:string;formula:string;boundary:string;raw:Raw[];next:string};
export const fmt=(n:number|null|undefined,d=2)=>valid(n)?Number(n).toLocaleString('zh-CN',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
export const pct=(n:number|null|undefined)=>valid(n)?`${Number(n)>0?'+':''}${fmt(n)}%`:'未知';
const rawUnit=(r:Row|undefined,field:string)=>{
 const currency=typeof r?.currency==='string'?r.currency.trim():'';
 if(!currency)return '币种未知（单位未确认）';
 const label=({CNY:'元 CNY',USD:'美元 USD',HKD:'港元 HKD'} as Record<string,string>)[currency]||currency;
 return label+(field==='basic_eps'?'/股':'');
};
export function diagnose(data:Dataset,selected?:number,days=120){
 const rows=(c:string,k:string)=>data.feeds[`${c}:${k}`]?.rows||[];
 const income=rows('000333.SZ','income-statements'); const cur=income.find(r=>r.period_end_ms===selected)||income[0];
 const prev=samePeriod(income,cur,true);const cash=samePeriod(rows('000333.SZ','cash-flow-statements'),cur);const oldCash=samePeriod(rows('000333.SZ','cash-flow-statements'),cur,true);
 const bal=samePeriod(rows('000333.SZ','balance-sheets'),cur);const oldBal=samePeriod(rows('000333.SZ','balance-sheets'),cur,true);
 const val=data.feeds.valuation?.rows.find(r=>r.thscode==='000333.SZ');const market=priceStats(data.feeds.history?.rows||[],days);
 const value=(r:Row|undefined,k:string)=>r?.currency==='CNY'&&valid(r[k])?r[k]:null;
 const rev=value(cur,'operating_income'),profit=value(cur,'parent_holder_net_profit'),cfo=value(cash,'act_cash_flow_net');
 const metrics={revenue:rev,profit,cfo,revenueGrowth:growth(rev,value(prev,'operating_income')),profitGrowth:growth(profit,value(prev,'parent_holder_net_profit')),cashGrowth:growth(cfo,value(oldCash,'act_cash_flow_net')),cashRatio:ratio(cfo,value(cur,'net_profit')),grossMargin:margin(rev,value(cur,'operating_costs')),receivableGrowth:growth(value(bal,'accounts_receivable'),value(oldBal,'accounts_receivable')),debtRatio:ratio(value(bal,'total_debt'),value(bal,'assets_total')),freeCash:difference(cfo,value(cash,'pay_fixed_assets_etc_cash'))};
 const raw=(kind:string,r:Row|undefined,fields:string[],code='000333.SZ'):Raw[]=>fields.map(field=>({field,value:r?.[field]??null,unit:rawUnit(r,field),period:periodName(r),source:`扶摇 · ${code}`,url:data.feeds[`${code}:${kind}`]?.url||'https://fuyao.aicubes.cn/docs/',published:dateCN(r?.report_date_ms),requestId:data.feeds[`${code}:${kind}`]?.requestId}));
 const pub=(field:string,n:number,page=7):Raw=>({field,value:n,unit:'元 CNY（原文千元 × 1,000）',period:'2026中报',source:filing.title,url:filing.url+`#page=${page}`,published:filing.published});
 const ev:Evidence[]=[];const cashOk=valid(metrics.cashRatio);
 ev.push({id:'cash',title:cashOk?`经营现金流为净利润的 ${fmt(metrics.cashRatio)} 倍`:'现金流覆盖情况尚无法判断',body:cashOk?'经营现金净流入与合并净利润对照，为盈利含金量提供一个观察角度。':'缺少同期经营现金流或有效的合并净利润，不能用零值替代。',dimension:'经营质量',direction:cashOk?(Number(metrics.cashRatio)>=1?'positive':'negative'):'unknown',kind:cashOk?'事实':'待验证',value:cashOk?`${fmt(metrics.cashRatio)}×`:'未知',formula:'经营现金流净额 ÷ 合并净利润；同一报告期、年初至期末累计。',boundary:'分母使用合并净利润，与合并现金流口径一致；该比率不等于利润全部收现，也不证明未来持续性。',raw:[...raw('cash-flow-statements',cash,['act_cash_flow_net']),...raw('income-statements',cur,['net_profit'])],next:'应收、存货和经营性应付款的变化，分别贡献了多少现金流？'});
 ev.push({id:'growth',title:valid(metrics.profitGrowth)?`归母净利润同比 ${pct(metrics.profitGrowth)}`:'同比趋势缺少可比期',body:`营业收入同比 ${pct(metrics.revenueGrowth)}，经营现金流同比 ${pct(metrics.cashGrowth)}。三者需要一起看。`,dimension:'财务趋势',direction:valid(metrics.profitGrowth)?(Number(metrics.profitGrowth)>=0?'positive':'negative'):'unknown',kind:valid(metrics.profitGrowth)?'事实':'待验证',value:pct(metrics.profitGrowth),formula:'（本期累计值 ÷ 上年同报告期累计值 − 1）× 100%；上年值 ≤ 0 时不展示普通增长率。',boundary:'中报是上半年累计数，三季报是前三季度累计数，不把相邻累计期当作单季环比。',raw:[...raw('income-statements',cur,['operating_income','parent_holder_net_profit']),...raw('income-statements',prev,['operating_income','parent_holder_net_profit']),...raw('cash-flow-statements',cash,['act_cash_flow_net']),...raw('cash-flow-statements',oldCash,['act_cash_flow_net'])],next:'归母增长与扣非增长是否一致？'});
 ev.push({id:'receivable',title:valid(metrics.receivableGrowth)?`期末应收账款同比 ${pct(metrics.receivableGrowth)}`:'应收占用仍需核实',body:'应收账款是期末余额，需要结合收入增长、账龄及坏账计提判断，不能只看余额增减。',dimension:'经营质量',direction:valid(metrics.receivableGrowth)&&valid(metrics.revenueGrowth)?(Number(metrics.receivableGrowth)>Number(metrics.revenueGrowth)?'negative':'neutral'):'unknown',kind:valid(metrics.receivableGrowth)?'事实':'待验证',value:pct(metrics.receivableGrowth),formula:'（本期期末应收账款 ÷ 上年同期期末应收账款 − 1）× 100%。',boundary:'应收余额增长快于收入只是一条需要研究的线索，不等于回款恶化。',raw:[...raw('balance-sheets',bal,['accounts_receivable']),...raw('balance-sheets',oldBal,['accounts_receivable'])],next:'应收账款账龄及信用减值是否同步变化？'});
 if(cur?.fiscal_year===2026&&cur?.fiscal_period==='Q2'){
 const g=growth(filing.facts.coreProfit,filing.facts.priorCoreProfit);
 ev.push({id:'core',title:'归母与扣非净利润走势分化',body:`公告披露归母净利润同比 ${pct(growth(filing.facts.parentProfit,filing.facts.priorParentProfit))}，扣非归母净利润同比 ${pct(g)}。${filing.explanation}`,dimension:'风险',direction:'conflict',kind:'分析推断',value:pct(g),formula:'两种利润分别与上年同期比较；扣非归母净利润同比 =（19,595,179 ÷ 26,235,399 − 1）× 100%。原文单位千元。',boundary:'两组数字可同时成立，属于经济含义与会计分类差异，不是数据错误。公司解释仍需结合附注验证。',raw:[pub('扣非归母净利润',filing.facts.coreProfit),{...pub('上年同期扣非归母净利润',filing.facts.priorCoreProfit),period:'2025中报'},pub('归母净利润',filing.facts.parentProfit),{...pub('上年同期归母净利润',filing.facts.priorParentProfit),period:'2025中报'}],next:'衍生工具收益能否持续？汇兑损失与套期收益的经济抵消程度如何？'});
 }
 const pe=val?.pe_ttm;ev.push({id:'valuation',title:valid(pe)&&pe>0?`市盈率 TTM ${fmt(pe)} 倍`:'估值暂不具备常规比较条件',body:'可与格力电器、海尔智家同口径比较，但业务结构、增长与资本结构均有差异。',dimension:'估值',direction:valid(pe)&&pe>0?'neutral':'unknown',kind:valid(pe)&&pe>0?'事实':'待验证',value:valid(pe)&&pe>0?`${fmt(pe)}×`:'未知',formula:'上游 PE TTM（最近十二个月）指标，原样读取；不与 MRQ 混用。',boundary:'当前估值不随历史财务期次回溯。数据源没有历史估值序列，不能声称处于历史低位，也不能仅凭低 PE 判断便宜。',raw:data.feeds.valuation?.rows.map(r=>({field:'pe_ttm',value:r.pe_ttm,unit:'倍',period:dateCN(data.feeds.valuation?.asOf),source:`扶摇 · ${r.name||r.thscode}`,url:data.feeds.valuation.url,requestId:data.feeds.valuation.requestId}))||[],next:'估值差异能否由盈利质量、业务组合和增长差异解释？'});
 const bars=market.bars;ev.push({id:'market',title:valid(market.change)?`区间价格变化 ${pct(market.change)}`:'行情区间数据不足',body:`最近 ${bars.length} 个可用交易日，最大回撤 ${valid(market.maxDrawdown)?fmt(market.maxDrawdown)+'%':'未知'}。`,dimension:'行情特征',direction:'neutral',kind:valid(market.change)?'事实':'待验证',value:pct(market.change),formula:'区间涨跌幅 =（末日收盘价 ÷ 首日收盘价 − 1）× 100%；最大回撤按各日收盘价相对此前峰值计算。',boundary:'前复权日收盘价；不是投资总回报，不预测后市。缺失交易日可能影响结果。',raw:bars.length?[{field:'close_price（区间首日）',value:bars[0].close_price,unit:'元/股，前复权',period:dateCN(bars[0].date_ms),source:'扶摇 · 日 K 线',url:data.feeds.history.url},{field:'close_price（区间末日）',value:bars.at(-1).close_price,unit:'元/股，前复权',period:dateCN(bars.at(-1).date_ms),source:'扶摇 · 日 K 线',url:data.feeds.history.url},...([['回撤峰值收盘价',market.drawdownPeak],['回撤谷值收盘价',market.drawdownTrough]] as const).filter(([,r])=>!!r).map(([field,r])=>({field,value:r.close_price,unit:'元/股，前复权',period:dateCN(r.date_ms),source:'扶摇 · 日 K 线',url:data.feeds.history.url,requestId:data.feeds.history.requestId}))]:[],next:'区间内有哪些已披露事件？它们与价格变化只有时间重合，还是有进一步证据？'});
 ev.push({id:'inventory',title:'存货周转与订单：仍有证据缺口',body:'本版基础财务接口未提供存货及账龄明细，也未接入实时订单与全部最新公告。',dimension:'风险',direction:'unknown',kind:'待验证',value:'待验证',formula:'不计算、不补零。',boundary:'数据缺失不代表不存在风险；公告整理截至 2026-08-29，并非完整实时事件流。',raw:[],next:'沿半年报附注检查存货、账龄与现金流调节表，并检索此后公告。'});
 const peers=data.companies.map(c=>{const r=samePeriod(rows(c.code,'income-statements'),cur);const p=samePeriod(rows(c.code,'income-statements'),cur,true);const cf=samePeriod(rows(c.code,'cash-flow-statements'),cur);return {...c,period:periodName(r),revenue:value(r,'operating_income'),profitGrowth:growth(value(r,'parent_holder_net_profit'),value(p,'parent_holder_net_profit')),margin:margin(value(r,'operating_income'),value(r,'operating_costs')),cashRatio:ratio(value(cf,'act_cash_flow_net'),value(r,'net_profit')),pe:data.feeds.valuation?.rows.find(v=>v.thscode===c.code)?.pe_ttm??null,raw:[...raw('income-statements',r,['operating_income','operating_costs','parent_holder_net_profit','net_profit'],c.code),...raw('income-statements',p,['parent_holder_net_profit'],c.code),...raw('cash-flow-statements',cf,['act_cash_flow_net'],c.code)]};});
 ev.push({id:'peers',title:'在同报告期内比较三家家电企业',body:'以营业收入规模、毛利率、利润增长和现金流覆盖度描述相对位置。样本仅三家公司，不代表全行业排名。',dimension:'行业位置',direction:'neutral',kind:'事实',formula:'财务按相同财年与报告期对齐；毛利率 =（营业收入 − 营业成本）÷ 营业收入。',boundary:'美的、格力、海尔业务构成与海外布局不同，只作为有限可比样本。',raw:peers.flatMap(p=>p.raw),next:'如果按业务分部而非集团整体比较，结论是否改变？'});
 ev.push({id:'event',title:'已披露事件：境外可转债融资',body:filing.event,dimension:'重要事件',direction:'neutral',kind:'事实',formula:'公告摘要第 4 页第三节，事件发生于 2026-05-06。',boundary:'事件资料截至 2026-08-29；募集资金用途计划不等于已实现回报；不自动归因为股价变化。',raw:[{field:'事件日期',value:'2026-05-06',unit:'日期',period:'2026中报披露',source:'2026 半年度报告摘要 · 第 4 页',url:filing.summaryUrl+'#page=4',published:filing.published}],next:'转股条款、未来稀释和资金实际使用情况如何？'});
 const checks=cur?.fiscal_year===2026&&cur?.fiscal_period==='Q2'?[['营业收入',rev,filing.facts.revenue],['归母净利润',profit,filing.facts.parentProfit],['经营现金流',cfo,filing.facts.cfo]].map(([label,a,b])=>({label,status:!valid(a)?'missing':Math.abs(Number(a)-Number(b))<1000?'matched':'conflict'})):[];
 const quality=assessQuality(data,cur,selected);
 for(const q of quality.filter(q=>['stale','unknown','missing'].includes(q.status))){
  const affected=q.id==='financial'?['cash','growth','receivable','peers']:q.id==='valuation'?['valuation']:q.id==='market'?['market']:[];
  for(const e of ev.filter(e=>affected.includes(e.id))){e.kind='待验证';e.direction='unknown';e.body=`${q.label}时效或完整性未通过检查。${q.message} 已有数值只供历史核对。`;e.boundary=q.message+' '+e.boundary;}
 }
 const primaryPeer=peers.find(p=>p.code==='000333.SZ');const comparison=peers.filter(p=>p.code!=='000333.SZ'&&valid(p.revenue)&&valid(p.margin));
 const peerEvidence=ev.find(e=>e.id==='peers')!;
 if(primaryPeer&&comparison.length&&valid(primaryPeer.revenue)&&valid(primaryPeer.margin)&&peerEvidence.kind==='事实')peerEvidence.body=`本样本中，美的营业收入高于 ${comparison.filter(p=>Number(primaryPeer.revenue)>Number(p.revenue)).length} 家可比公司，毛利率高于 ${comparison.filter(p=>Number(primaryPeer.margin)>Number(p.margin)).length} 家。集团规模与盈利结构应分开比较；这不是行业市场份额排名。`;
 if(!comparison.length||!valid(primaryPeer?.revenue)){peerEvidence.kind='待验证';peerEvidence.direction='unknown';peerEvidence.body='缺少同报告期的可比公司数据，不能判断相对位置。';}
 return {cur,prev,cash,bal,metrics,evidence:ev,peers,market,periods:income.slice(0,8),checks,quality};
}
